### ISSUE TITLE
will there be a parser?

### ISSUE THREAD

**Issue by fdncred** [fzechert/ansi-control-codes#3]
Nice crate! Thanks for creating it.

One thing that would be cool is if one could create a program, pass it a string of escape sequences, and then have the code parsed and mapped into your create. I kind of think of this as a traslator where you could say, "what does this escape sequence do?".

**Comment by fzechert** [comment]
Do you have any example of what you would expect this to look like?

The problem with a parser in this library is, that - at least in the current scope of the library - it does not bring you any additional functionality.

This library is more or less a collection of constants that translate into strings.
For example, there is `ansi_control_codes::c0::BEL` which is just nice syntax for the string with the byte value `0x7`.

Imagine having a parser that accepts a byte array `[0x7]` or another string with `0x7` in it, it would be translated to `BEL`, which is in turn just again a `0x7`. So this `parser` would have done nothing.

So, what would such a parser return instead?

**Comment by fdncred** [comment]
Sure. Personally, I'd like to build it into nushell since I'm one of the maintainers. Or maybe make a nushell plugin. Or even a completely separate rust tool. 

Assuming it was a nushell command, it would work and output something like this. I'm just guessing at the explanation. I'm definitely not sure what this sequence does.
```nushell
> ansi translate "\x1b[?0u\x1b[?62;22c"
╭─#─┬───Sequence───┬───────────────────Name───────────────────┬───────────────────Explanation────────────────────╮
│ 0 │ \x1b[?0u     │ your structure name here in display mode │ query terminal default state or initial settings │
│ 1 │ \x1b[?62;22c │ your structure name here in display mode │ maybe set row and column                         │
╰───┴──────────────┴──────────────────────────────────────────┴──────────────────────────────────────────────────╯

```

**Comment by fzechert** [comment]
I will try to implement something like that. But it might take a while. It was never planned to have something like this in this library. But since you are not the first person asking for a parser, I will try to add one for the next major version of the library.

**Comment by fzechert** [comment]
First step is done. The master branch now contains a working parser implementation.

Here is an example of how it works (requires the feature `parser` to be active)

```rust
use ansi_control_codes::c1::NEL;
use ansi_control_codes::parser::{TokenStream, Token};

let to_be_parsed = format!("This text{}is spread across{}multiple lines.", NEL, NEL);
let parsed = TokenStream::from(&to_be_parsed);

let parts: Vec<Token> = parsed.collect();
println!("{:?}", parts);

assert_eq!(parts[0], Token::String("This text"));
assert_eq!(parts[1], Token::ControlFunction(NEL));
assert_eq!(parts[2], Token::String("is spread across"));
assert_eq!(parts[3], Token::ControlFunction(NEL));
assert_eq!(parts[4], Token::String("multiple lines."));
```

But this is only half of what is needed to get your example working. Because what is still missing is the explanation part of it.

**Comment by fdncred** [comment]
So far, so good. Nice work. Thanks for the update.

**Comment by fzechert** [comment]
Parser and Explanation module have been published in the latest release (v1.0.0 and v1.0.1).
Thank's for your patience.

Here is an example:

```rust
use ansi_control_codes::c1::NEL;
use ansi_control_codes::parser::{TokenStream, Token};
use ansi_control_codes::explain::Explain;

let example = "\x1b[0u\x1b[62c\x1b[23;6H";
let result = TokenStream::from(&example).collect::<Vec<Token>>();

for (i, part) in result.iter().enumerate() {
    match part {
        Token::String(string) => println!("{}. Normal String: {}", i, string),
        Token::ControlFunction(control_function) => {
            println!(
                "{}. Control Function: {} ({})",
                i,
                control_function.short_name().unwrap_or_default(),
                control_function.long_name()
            );
            println!(
                "Short description: {}",
                control_function.short_description()
            );
            println!("Long description: {}", control_function.long_description());
        }
    }
    if i < (result.len() - 1) {
        println!("---------------------");
    }
}
```

This will produce the following output
```
0. Control Function:  (Private Use / Experimental Use)
Short description: Reserved for private use / not standardized.
Long description: Reserved for private use / not standardized.
---------------------
1. Control Function: DA (Device Attributes)
Short description: The device sending this identifies as device with code 62.
Long description: The device sending this identifies as device with code 62.
---------------------
2. Control Function: CUP (Cursor Position)
Short description: Move the active position to line 23 and character 6.
Long description: Causes the active presentation position to be moved in the presentation component to the 23rd line
position according to the line progression, and to the 6 character position according to the character path.
```

**Comment by fdncred** [comment]
oh, wow, this is very cool. thanks so much for all the work and effort. i'm excited to play around with this!

**Comment by fdncred** [comment]
When it fails on a sequence like in my example. Do you think that means, the sequence is invalid or does your software just not understand it yet?
```
Example: "\u{1b}[?0u\u{1b}[?62;22c"

0. Control Function:  (Private Use / Experimental Use)
Short description: Reserved for private use / not standardized.
Long description: Reserved for private use / not standardized.
---------------------
1. Control Function: DA (Device Attributes)
thread 'main' panicked at /Users/fdncred/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ansi-control-codes-1.0.1/src/explain.rs:2665:22:
Expected valid Device Attributes.: ParseIntError { kind: InvalidDigit }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by fzechert** [comment]
The problem here is the last control function in your example input `\u{1b}[62;22c`.
This is an invalid control function.

`\u{1b}` (a.k.a. `ESC`) and `[` start a control sequence.
According to the standard, this can be followed by any number of **numeric** arguments, each argument separated by `;`.

In your example, those arguments would be `?62` and `22`.
Then the control function is terminated by the identifier `c` (which is Device Attributes `DA` in your example).
The problem here is with the first argument. `?62` is not a valid numeric value.

Where does your example string come from? Since `DA` (Device Attributes) also only accepts one parameter, not two, according to the specification.

**Comment by fdncred** [comment]
Sorry but here's another question. With this escape sequence
```rust
    let example = "\x1b]10;?\x07\x1b]11;?\x07\x1b]4;0;?\x07\x1b]4;1;?\x07\x1b]4;2;?\x07\x1b]4;3;?\x07\x1b]4;4;?\x07\x1b]4;5;?\x07\x1b]4;6;?\x07\x1b]4;7;?\x07\x1b]4;8;?\x07\x1b]4;9;?\x07\x1b]4;10;?\x07\x1b]4;11;?\x07\x1b]4;12;?\x07\x1b]4;13;?\x07\x1b]4;14;?\x07\x1b]4;15;?\x07";
```
it's querying the terminal to get the theme. if your terminal supports this querying it returns something like this which are rgb colors for each entry in the palette 0-16 and fg + bg colors.
```
10;rgb:b3b3/b3b3/b3b311;rgb:0000/0000/00004;0;rgb:0000/0000/00004;1;rgb:cccc/5555/55554;2;rgb:5555/cccc/55554;3;rgb:cdcd/cdcd/55554;4;rgb:5555/5555/cccc4;5;rgb:cccc/5555/cccc4;6;rgb:7a7a/caca/caca4;7;rgb:cccc/cccc/cccc4;8;rgb:5555/5555/55554;9;rgb:ffff/5555/55554;10;rgb:5555/ffff/55554;11;rgb:ffff/ffff/55554;12;rgb:5555/5555/ffff4;13;rgb:ffff/5555/ffff4;14;rgb:5555/ffff/ffff4;15;rgb:ffff/ffff/ffff
```
The explanation returns things like this
```

0. Control Function: [OSC] ln: (Operating System Command) part: [ControlFunction(
    ControlFunction {
        function_type: C1,
        function: "05/13",
        parameters: [],
    },
)]
Short description: Opening delimiter of a control string for operating system use.
Long description: Opening delimiter of a control string for operating system use. The command string following may consist of a sequence of bit combinations in the range 00/08 to 00/13 and 02/00 to 07/14. The control string is closed by the terminating delimiter 'String Terminator' (ST). The interpretation of the command string depends on the relevant operating system.
---------------------
1. Normal String: 10;?
---------------------
2. Control Function: [BEL] ln: (Bell) part: [ControlFunction(
    ControlFunction {
        function_type: C0,
        function: "00/07",
        parameters: [],
    },
)]
Short description: Calls for attention.
Long description: Calls for the attention of the user by controlling an alarm or attention device.
```
which I guess is probably right but doesn't really say what the ansi escape sequence does. I'm wondering if the `?` query terminal sequence, as in `\u{1b}]10;?\u{7}` is just not understood or if there is just no way to know what it means without understanding the system and context?

**Comment by fzechert** [comment]
Things like querying terminals for color themes are not part of the standard definition of 1991. They might work fine across terminals due to multiple terminal emulators agreeing on a common set of commands, but cannot be understood by this library.

According to the standard, neither `\u{1b}]` is a valid beginning of a control sequence (a control sequence starts with `\u{1b}[`), nor is `\u{7}` a valid end of a control sequence (final byte, or intermediate and final byte).

This crate only understands all the escape codes defined in the ecma standard.

**Comment by fdncred** [comment]
> Where does your example string come from?

It's been a while but IIRC, this was found when debugging some nushell code with [escape-artist](https://github.com/rgwood/escape-artist).

**Comment by fdncred** [comment]
> This crate only understands all the escape codes defined in the ecma standard.

ok, understood. at least that explains it. this is exactly why i was looking at your crate, to find some tool that understands all standards and can parse and display what is going on. if people invent different escape sequences, i guess those aren't standard which could be why some terminals support them and some do not. there's a lot of "shell integration" escapes that probably aren't standard at all but really what i'm looking to understand better. I started making a list of these sequences here https://gist.github.com/fdncred/c649b8ab3577a0e2873a8f229730e939/

**Comment by fzechert** [comment]
Yes, a lot of the control codes in the world of terminal emulation are not standardized. That's why, for example, more sophisticated programs rely on `termcap`, which provides a database of all special oddities that are understood by some but not by all terminals.

You can imagine the ECMA-48 standard / the ANSI escape codes only as a subset of those, that people managed to standardize properly.
